// web/src/pages/albums/index.vue
<script setup>
import AlbumCard from '../../components/AlbumCard.vue';
</script>

<script>
import { API_URL } from '../../config.js';

export default {
    data() {
        return {
            albums: []
        }
    },

    created() {
        this.fetchPage(1);
    },

    methods: {
        async fetchPage(page) {
            const response = await fetch(`${API_URL}/albums?page=${page}`);
            const newAlbums = await response.json();
            if (newAlbums.length > 0) {
                this.albums.push(...newAlbums);
                this.fetchPage(page + 1);
            }
        }
    }
};
</script>

<template>
    <div>
        <h2 class="title">Albums</h2>
        <div class="columns is-multiline">
            <div class="column is-one-fifth" v-for="album in albums" :key="album.id">
                <album-card :album="album" />
            </div>
        </div>
    </div>
</template>

// web/src/routes/albums/index.svelte
<script context="module">
import { API_URL } from '../../config.js';

export async function load({ fetch }) {
    const response = await fetch(`${API_URL}/albums`);
    return {
        status: response.status,
        props: {
            albums: response.ok && (await response.json())
        }
    };
};
</script>

<script>
import AlbumCard from '../../components/AlbumCard.svelte';

export let albums;

async function fetchPage(page) {
    const response = await fetch(`${API_URL}/albums?page=${page}`);
    const newAlbums = await response.json();
    if (newAlbums.length > 0) {
        albums.push(...newAlbums);
        albums = albums;
        fetchPage(page + 1);
    }
}
fetchPage(2);
</script>

<svelte:head>
    <title>Albums - BassieMusic</title>
</svelte:head>

<h2 class="title">Albums</h2>

<div class="columns is-multiline">
    {#each albums as album}
        <div class="column is-one-fifth">
            <AlbumCard album={album} />
        </div>
    {/each}
</div>
