// web/src/pages/artists/index.vue
<script>
import { API_URL } from '../../config.js';

export default {
    data() {
        return {
            artists: []
        }
    },

    created() {
        this.fetchPage(1);
    },

    methods: {
        async fetchPage(page) {
            const response = await fetch(`${API_URL}/artists?page=${page}`);
            const newArtists = await response.json();
            if (newArtists.length > 0) {
                this.artists.push(...newArtists);
                this.fetchPage(page + 1);
            }
        }
    }
};
</script>

<template>
    <div>
        <h2 class="title">Artists</h2>
        <div class="columns is-multiline">
            <div class="column is-one-fifth" v-for="artist in artists" :key="artist.id">
                <router-link class="card" :to="`/artists/${artist.id}`">
                    <div class="card-image" :style="{ backgroundImage: `url(${artist.image})` }"></div>
                    <div class="card-content">
                        <h3 class="title is-6">{{ artist.name }}</h3>
                    </div>
                </router-link>
            </div>
        </div>
    </div>
</template>

// web/src/routes/liked/artists/+page.svelte
<script>
    import ArtistCard from "../../../components/artist-card.svelte";

    export let data;
    let { token, authUser, artists } = data;

    async function fetchPage(page) {
        const response = await fetch(
            `${import.meta.env.VITE_API_URL}/users/${authUser.id}/liked_artists?${new URLSearchParams({
                page,
            })}`,
            {
                headers: {
                    Authorization: `Bearer ${token}`,
                },
            }
        );
        const { data: newArtists, pagination } = await response.json();
        artists.push(...newArtists);
        artists = artists;
        if (artists.length != pagination.total) {
            fetchPage(page + 1);
        }
    }
    if (artists.length != data.total) {
        fetchPage(2);
    }
</script>

<svelte:head>
    <title>Artists - Liked - BassieMusic</title>
</svelte:head>

<div class="tabs">
    <ul>
        <li class="is-active"><a href="/liked/artists">Artists</a></li>
        <li><a href="/liked/albums">Albums</a></li>
        <li><a href="/liked/tracks">Tracks</a></li>
    </ul>
</div>

<div class="content">
    <h1 class="title">Liked Artists</h1>

    <div class="columns is-multiline">
        {#each artists as artist}
            <div class="column is-one-fifth">
                <ArtistCard {artist} />
            </div>
        {/each}
    </div>
</div>
